"""``loopflow init`` 子命令 — 脚手架初始化。

在目标路径生成 Loop Engineering 所需的文件结构：

- ``LOOP.md``：循环配置文档（活跃循环列表、节奏、级别、worktree 策略）
- ``STATE.md``：初始状态文件（当前迭代、待办、已完成、暂停标志）
- ``loop-budget.yaml``：预算配置（daily_cap, threshold 等）
- ``loop-constraints.md``：约束文件（路径保护、行为规则）
- ``.claude/skills/loop-triage/SKILL.md``（仅 ``--tool claude`` 时生成）

用法::

    loopflow init                          # 在当前目录初始化（默认 daily-triage / claude / L1）
    loopflow init /tmp/proj --pattern daily-triage --tool claude --level L1
"""

from __future__ import annotations

from pathlib import Path

import click
from rich.console import Console

from loopkits.cli.audit import run_audit
from loopkits.core.loop import TrustLevel
from loopkits.patterns.registry import get, list_patterns

__all__ = ["init"]

console: Console = Console()


def _render_loop_md(
    pattern_name: str,
    level: str,
    tool: str,
    cadence: str,
    description: str,
) -> str:
    """生成 LOOP.md 内容。"""
    return f"""# LOOP.md — {pattern_name}

This file documents how this project is operated with Loop Engineering patterns.
Generated by `loopflow init`.

## Active Loops

### {pattern_name} ({level} — {('automated + report' if level == 'L1' else 'assisted' if level == 'L2' else 'full auto')})
- Cadence: {cadence or '1d'}
- Pattern: `{pattern_name}` — {description}
- State: `STATE.md` (updated by loop on each run; human reviews periodically)
- Tool: `{tool}`
- Phase: {('Report-only. Human reviews and decides actions.' if level == 'L1' else 'Assisted fixes in worktree; verifier required; no auto-merge.' if level == 'L2' else 'Full auto with strict constraints and verifier gates.')}
- Handoff: Design decisions, large refactors, new pattern acceptance.

## Multi-loop coordination

If running multiple loops, priority order:
CI Sweeper → PR Babysitter → Dependency Sweeper → Post-Merge / Changelog Drafter (off-peak) → Daily Triage (report).

## Worktrees

- Any unattended code-change experiment runs in an **isolated git worktree** per attempt.
- One worktree per fix; discard after verifier REJECT or human escalation.
- Use `loopflow worktree create --run-id <id> --pattern {pattern_name}` to create a worktree.

## Budget & Observability

- Token caps: `loop-budget.yaml`
- Run history: appended to `STATE.md` by the loop on each run
- Estimate: `loopflow cost {pattern_name} --runs 10`
- Kill switch: `loop-pause-all` flag in `STATE.md` (set via `loopflow state pause`)

## Safety & Gates

- No auto-merge on main except trivial dependency patches (allowlist + verifier)
- Denylist: see `loop-constraints.md`
- Live loop state: `STATE.md` at repo root

## How to run locally

```bash
loopflow run {pattern_name} --level {level}
loopflow audit . --suggest
loopflow state show
```

---

*This file is both documentation and the seed for the loops that maintain this project.*
"""


def _render_state_md(pattern_name: str, description: str) -> str:
    """生成 STATE.md 内容。"""
    return f"""# Loop State — {pattern_name}

Last run: (未运行)

## Current Iteration: 0

**Goal**: {description}

## High Priority (loop is acting or waiting on human)

<!-- Format:
- [ ] ID — one-line description
  Loop action: what the loop did last
  Human decision: (if any)
-->

—

## Watch List

<!-- Items to monitor but not act on yet -->

—

## Completed

—

## History

—

## Notes

Loop initialized by `loopflow init`. Use `loopflow state pause` to activate
`loop-pause-all` kill switch.

---
Run log: 由 LoopKits 自动维护。
"""


def _render_budget_yaml(pattern_name: str, level: str) -> str:
    """生成 loop-budget.yaml 内容。"""
    # L3 给更高预算，L2 中等，L1 较低
    cap = 200_000 if level == "L3" else 100_000 if level == "L2" else 50_000
    return f"""# Loop Budget — {pattern_name}
# 由 loopflow init 生成；可用 loopflow cost 估算实际消耗
daily_cap: {cap}
spent: 0
threshold: 0.8
degraded: false
"""


def _render_constraints_md(pattern_name: str) -> str:
    """生成 loop-constraints.md 内容。"""
    return f"""# Loop Constraints — {pattern_name}

> Add rules below with `/constraints <rule>` in your agent.
> The `loop-constraints` skill reads this file at the start of every run.
> Constraints here are **binding** — the agent MUST follow them.

## Push & Merge
- Don't push before telling me
- Never auto-merge to main without human approval
- Always create a draft PR first; let me review before marking ready

## Paths
- Never edit .env, .env.*, auth/, payments/, secrets/, credentials/
- Never edit infrastructure configs without human approval
- Never edit loop-budget.yaml or loop-constraints.md directly

## Code
- Always run tests before proposing a fix
- Never disable tests to make CI green
- Never refactor unrelated code — one fix per run
- Max 3 fix attempts per item; escalate after

## Communication
- Always tell me what you're about to do before doing it
- Never close an issue or PR without my approval

## Budget
- If token spend hits 80% of daily cap, switch to report-only
- If loop-pause-all is active, exit immediately

---
<!-- Add your own rules below. Use plain English. The loop reads this verbatim. -->
"""


def _write_if_absent(path: Path, content: str) -> bool:
    """如果文件不存在则写入，返回是否写入。已存在则跳过。"""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


@click.command()
@click.argument("path", required=False, default=".")
@click.option(
    "--pattern",
    "pattern_name",
    default="daily-triage",
    help="循环模式名称（如 daily-triage / pr-babysitter）",
)
@click.option(
    "--tool",
    type=click.Choice(["claude", "codex", "cursor"]),
    default="claude",
    help="目标工具（影响生成的技能文件结构）",
)
@click.option(
    "--level",
    type=click.Choice(["L1", "L2", "L3"]),
    default="L1",
    help="信任级别：L1 仅报告 / L2 辅助修复 / L3 全自动",
)
def init(path: str, pattern_name: str, tool: str, level: str) -> None:
    """在 PATH 生成 Loop Engineering 脚手架文件。

    默认在当前目录初始化，使用 daily-triage 模式、claude 工具、L1 级别。
    已存在的文件会被跳过（不覆盖）。
    """
    root = Path(path).resolve()

    # 校验模式是否存在
    pattern_cls = get(pattern_name)
    if pattern_cls is None:
        available = [m.name for m in list_patterns()]
        click.echo(
            f"模式不存在：{pattern_name}。可用模式：{', '.join(available)}",
            err=True,
        )
        raise SystemExit(1)

    meta = pattern_cls.meta
    # 创建模式实例以调用 to_skill_md
    pattern_instance = pattern_cls(level=TrustLevel(level))

    # 确保目标目录存在
    root.mkdir(parents=True, exist_ok=True)

    console.print(f"\n[bold cyan]LoopFlow Init[/bold cyan] — 目标目录: {root}")
    console.print(
        f"模式: [magenta]{pattern_name}[/magenta] | "
        f"工具: [magenta]{tool}[/magenta] | "
        f"级别: [magenta]{level}[/magenta]\n"
    )

    created: list[str] = []
    skipped: list[str] = []

    # 1. LOOP.md
    loop_md_path = root / "LOOP.md"
    if _write_if_absent(
        loop_md_path,
        _render_loop_md(pattern_name, level, tool, meta.cadence, meta.description),
    ):
        created.append(str(loop_md_path.relative_to(root)))
    else:
        skipped.append(str(loop_md_path.relative_to(root)))

    # 2. STATE.md
    state_md_path = root / "STATE.md"
    if _write_if_absent(
        state_md_path,
        _render_state_md(pattern_name, meta.description),
    ):
        created.append(str(state_md_path.relative_to(root)))
    else:
        skipped.append(str(state_md_path.relative_to(root)))

    # 3. loop-budget.yaml
    budget_path = root / "loop-budget.yaml"
    if _write_if_absent(budget_path, _render_budget_yaml(pattern_name, level)):
        created.append(str(budget_path.relative_to(root)))
    else:
        skipped.append(str(budget_path.relative_to(root)))

    # 4. loop-constraints.md
    constraints_path = root / "loop-constraints.md"
    if _write_if_absent(
        constraints_path,
        _render_constraints_md(pattern_name),
    ):
        created.append(str(constraints_path.relative_to(root)))
    else:
        skipped.append(str(constraints_path.relative_to(root)))

    # 5. 工具特定技能文件
    if tool == "claude":
        skill_dir = root / ".claude" / "skills" / "loop-triage"
        skill_md_path = skill_dir / "SKILL.md"
        if _write_if_absent(skill_md_path, pattern_instance.to_skill_md()):
            created.append(str(skill_md_path.relative_to(root)))
        else:
            skipped.append(str(skill_md_path.relative_to(root)))

    # 输出创建/跳过清单
    if created:
        console.print("[bold green]✓ 已创建：[/bold green]")
        for f in created:
            console.print(f"  [green]+[/green] {f}")
    if skipped:
        console.print("\n[bold yellow]⚠ 已跳过（文件已存在）：[/bold yellow]")
        for f in skipped:
            console.print(f"  [yellow]≈[/yellow] {f}")
        console.print(
            "[dim]如需重新生成，请先删除对应文件或更换目标目录。[/dim]"
        )

    # Loop Ready 评分
    score, _ = run_audit(root)
    color = "green" if score >= 80 else "yellow" if score >= 60 else "red"
    console.print(
        f"\n[bold]Loop Ready 评分：[/bold] [{color}]{score}[/{color}]/100"
    )

    # 首条循环命令提示
    console.print("\n[bold cyan]下一步：运行你的首个循环[/bold cyan]")
    console.print(
        f"  [dim]$[/dim] [green]loopflow run[/green] {pattern_name} "
        f"--level {level}"
    )
    console.print(
        f"  [dim]$[/dim] [green]loopflow audit[/green] {root} --suggest"
    )
    console.print(
        f"  [dim]$[/dim] [green]loopflow state[/green] show\n"
    )
